#pragma once
#if !defined(MYLIB_CONSTANTS_H)
#define MYLIB_CONSTANTS_H 1

//Écrire constantes ici
const int CUBE_SIZE = 5;
const int DELAIDUCALCULULTRACOMPLEXEPOURCALCULERLANOTEQUEDANIELVADONNERAUMEILLEURTPDALGODUMONDE = 3;

#endif